---
development:
  cloud_name: dp4soym81
  api_key: '818235162633128'
  api_secret: oP1pJ37otcVHsemCnTIpb6BQEGI
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dp4soym81
  api_key: '818235162633128'
  api_secret: oP1pJ37otcVHsemCnTIpb6BQEGI
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dp4soym81
  api_key: '818235162633128'
  api_secret: oP1pJ37otcVHsemCnTIpb6BQEGI
  enhance_image_tag: true
  static_file_support: false
